import ClientProvider from "@/components/ClientProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SignInLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="bg-[#F3F4F2]">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}

